# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_outerproduct <- function(x) {
    .Call(`_BayesHFLM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BayesHFLM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BayesHFLM_rcpparma_bothproducts`, x)
}

myfirstfunc <- function() {
    .Call(`_BayesHFLM_myfirstfunc`)
}

sampleMVN <- function(ell, Qc) {
    .Call(`_BayesHFLM_sampleMVN`, ell, Qc)
}

data_matrix <- function(mymat, nc, nr) {
    .Call(`_BayesHFLM_data_matrix`, mymat, nc, nr)
}

constructMatrix <- function(Xvec, taus, Ss, Fk, Fk1, Psi, delta, nobs) {
    .Call(`_BayesHFLM_constructMatrix`, Xvec, taus, Ss, Fk, Fk1, Psi, delta, nobs)
}

mcmc_sampler <- function(Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter) {
    .Call(`_BayesHFLM_mcmc_sampler`, Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter)
}

mcmc_sampler2 <- function(Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter) {
    .Call(`_BayesHFLM_mcmc_sampler2`, Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter)
}

constructMatrix2 <- function(Xvec, taus, Ss, Fk, Fk1, Psi, delta, nobs) {
    .Call(`_BayesHFLM_constructMatrix2`, Xvec, taus, Ss, Fk, Fk1, Psi, delta, nobs)
}

mcmc_sampler3 <- function(Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter) {
    .Call(`_BayesHFLM_mcmc_sampler3`, Yvec, Ymat, Xvec, Xmat, taus, Ss, Fk, Fk1, Psi, Phi, Dmu, Db, Dalpha, Dc, delta, i1, i2, a, b, niter)
}

